version: "2"
linters:
  default: none
  enable:
    - errcheck
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: Potential HTTP request made with variable url
      - path: (.+)\.go$
        text: Potential file inclusion via variable
      - path: (.+)\.go$
        text: 'G115: integer overflow conversion int -> uint16'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
